
TRUNCATE cdm.care_site 
RESTART IDENTITY CASCADE;

TRUNCATE cdm.cdm_source 
RESTART IDENTITY CASCADE;

TRUNCATE cdm.condition_era 
RESTART IDENTITY CASCADE;

TRUNCATE cdm.condition_occurrence 
RESTART IDENTITY CASCADE;

TRUNCATE cdm.cost 
RESTART IDENTITY CASCADE;

TRUNCATE cdm.death 
RESTART IDENTITY CASCADE;

TRUNCATE cdm.device_exposure 
RESTART IDENTITY CASCADE;

TRUNCATE cdm.location 
RESTART IDENTITY CASCADE;

TRUNCATE cdm.measurement 
RESTART IDENTITY CASCADE;

TRUNCATE cdm.observation 
RESTART IDENTITY CASCADE;

TRUNCATE cdm.observation_period 
RESTART IDENTITY CASCADE;

TRUNCATE cdm.payer_plan_period 
RESTART IDENTITY CASCADE;

TRUNCATE cdm.person 
RESTART IDENTITY CASCADE;

TRUNCATE cdm.procedure_occurrence 
RESTART IDENTITY CASCADE;

TRUNCATE cdm.provider 
RESTART IDENTITY CASCADE;

TRUNCATE cdm.visit_occurrence 
RESTART IDENTITY CASCADE;