-- broadsea/sql/grant_permissions.sql
GRANT USAGE ON SCHEMA webapi TO PUBLIC;

GRANT ALL ON SCHEMA webapi TO
GROUP omop_admin;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA webapi TO omop_admin;

GRANT USAGE ON SCHEMA webapi TO
GROUP omop_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA webapi GRANT INSERT,
SELECT
, UPDATE, DELETE, REFERENCES, TRIGGER ON TABLES TO omop_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA webapi GRANT
SELECT
, USAGE ON SEQUENCES TO omop_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA webapi GRANT EXECUTE ON FUNCTIONS TO omop_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA webapi GRANT USAGE ON TYPES TO omop_app;

GRANT ALL ON SCHEMA cdm TO
GROUP omop_admin;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA cdm TO omop_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA cdm GRANT INSERT,
SELECT
, UPDATE, DELETE, REFERENCES, TRIGGER ON TABLES TO omop_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA cdm GRANT
SELECT
, USAGE ON SEQUENCES TO omop_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA cdm GRANT EXECUTE ON FUNCTIONS TO omop_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA cdm GRANT USAGE ON TYPES TO omop_app;

GRANT ALL ON SCHEMA vocab TO
GROUP omop_admin;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA vocab TO omop_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA vocab GRANT INSERT,
SELECT
, UPDATE, DELETE, REFERENCES, TRIGGER ON TABLES TO omop_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA vocab GRANT
SELECT
, USAGE ON SEQUENCES TO omop_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA vocab GRANT EXECUTE ON FUNCTIONS TO omop_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA vocab GRANT USAGE ON TYPES TO omop_app;

GRANT ALL ON SCHEMA results TO
GROUP omop_admin;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA results TO omop_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA results GRANT INSERT,
SELECT
, UPDATE, DELETE, REFERENCES, TRIGGER ON TABLES TO omop_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA results GRANT
SELECT
, USAGE ON SEQUENCES TO omop_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA results GRANT EXECUTE ON FUNCTIONS TO omop_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA results GRANT USAGE ON TYPES TO omop_app;

GRANT ALL ON SCHEMA temp TO
GROUP omop_admin;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA temp TO omop_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA temp GRANT INSERT,
SELECT
, UPDATE, DELETE, REFERENCES, TRIGGER ON TABLES TO omop_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA temp GRANT
SELECT
, USAGE ON SEQUENCES TO omop_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA temp GRANT EXECUTE ON FUNCTIONS TO omop_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA temp GRANT USAGE ON TYPES TO omop_app;

GRANT USAGE ON SCHEMA webapi TO omop_admin;

GRANT USAGE ON SCHEMA cdm TO omop_admin;

GRANT USAGE ON SCHEMA vocab TO omop_admin;

GRANT USAGE ON SCHEMA results TO omop_admin;

GRANT USAGE ON SCHEMA temp TO omop_admin;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA webapi TO omop_admin;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA cdm TO omop_admin;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA vocab TO omop_admin;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA results TO omop_admin;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA temp TO omop_admin;

GRANT USAGE ON SCHEMA webapi TO omop_app;

GRANT USAGE ON SCHEMA cdm TO omop_app;

GRANT USAGE ON SCHEMA vocab TO omop_app;

GRANT USAGE ON SCHEMA results TO omop_app;

GRANT USAGE ON SCHEMA temp TO omop_app;

GRANT INSERT, SELECT, UPDATE, DELETE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA webapi TO omop_app;

GRANT INSERT, SELECT, UPDATE, DELETE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA cdm TO omop_app;

GRANT INSERT, SELECT, UPDATE, DELETE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA vocab TO omop_app;

GRANT INSERT, SELECT, UPDATE, DELETE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA results TO omop_app;

GRANT INSERT, SELECT, UPDATE, DELETE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA temp TO omop_app;

